[package]
name = "ipr"
version = "0.1.0"
authors = ["oamam <chapa0106@gmail.com>"]
edition = "2018"
license = "MIT"
description = "The tool to output IPv4 informations"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.1"